services:
  postgresql:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "mediabox"
      POSTGRES_PASSWORD: "mediabox"
      POSTGRES_DB: "mediabox"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - "./mediabox-data/postgresql:/var/lib/postgresql/data"

  mediabox:
    build: .
    image: mediabox-dev:latest
    depends_on:
      - postgresql
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      MEDIABOX_HOST: "0.0.0.0"
      MEDIABOX_PORT: "8000"
      MEDIABOX_USE_TLS: "false"
      MEDIABOX_TLS_CERT: "server.crt"
      MEDIABOX_TLS_KEY: "server.key"
      MEDIABOX_DATABASE_DRIVER: "postgresql"
      MEDIABOX_DATABASE_DSN: "host=postgresql user=mediabox password=mediabox dbname=mediabox port=5432 sslmode=disable TimeZone=Asia/Shanghai"
      MEDIABOX_STORAGE_PATH: "mediabox-data/storage"
    volumes:
      - ".:/mediabox/src"

  mediabox-frontend:
    image: mediabox-dev:latest
    command: /bin/sh -c "cd /mediabox/src/frontend && npm run serve"
    ports:
      - "8080:8080"
    volumes:
      - ".:/mediabox/src"
